language: node_js
matrix:
  include:
    - node_js: "node"
    - node_js: "6"
dist: trusty
sudo: false
cache:
  directories:
    - node_modules
    - chrome
addons: # needed to run Chrome stable
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
before_script:
  - google-chrome --version
  - npm list
addons:
  chrome: stable
